"""added table muscle group

Revision ID: 9bf62e9c061c
Revises: 6832130862a2
Create Date: 2024-02-26 21:45:30.321249

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9bf62e9c061c'
down_revision: Union[str, None] = '6832130862a2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('muscle_group',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('muscle_group_name', sa.VARCHAR(length=255), nullable=True),
    sa.Column('muscle_group_image', sa.VARCHAR(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_muscle_group_id'), 'muscle_group', ['id'], unique=True)
    op.create_index(op.f('ix_muscle_group_muscle_group_image'), 'muscle_group', ['muscle_group_image'], unique=False)
    op.create_index(op.f('ix_muscle_group_muscle_group_name'), 'muscle_group', ['muscle_group_name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_muscle_group_muscle_group_name'), table_name='muscle_group')
    op.drop_index(op.f('ix_muscle_group_muscle_group_image'), table_name='muscle_group')
    op.drop_index(op.f('ix_muscle_group_id'), table_name='muscle_group')
    op.drop_table('muscle_group')
    # ### end Alembic commands ###
